/**
 * Mortgage Deals Demo Data - Scarlett Network Format
 * Realistic mortgage pipeline deals with Scarlett Network data structure
 */

export const MortgageDealsData = [
  // ============================================================
  // QUALIFY TO BUY - Initial consultation stage
  // ============================================================
  {
    key: "1",
    DealName: "Smith Family - Single Family Home",
    Stage: "Qualify To Buy",
    DealValue: "$485,000",
    Tags: "Pre-Qualification",
    ExpectedCloseDate: "2026-06-15",
    Probability: "85%",
    Status: "Open",
    BorrowerName: "Michael Smith",
    BorrowerPhone: "+1 (416) 555-0101",
    BorrowerEmail: "michael.smith@email.com",
    PropertyAddress: "123 Maple Street, Toronto, ON",
    PropertyType: "Single Family",
    LoanAmount: "$388,000",
    DownPayment: "$97,000",
    InterestRate: "5.24%",
    Lender: "Royal Bank of Canada",
    LoanOfficer: "Sarah Chen",
    Notes: "First-time homebuyer, excellent credit score",
  },
  {
    key: "2",
    DealName: "Johnson Couple - Condo",
    Stage: "Qualify To Buy",
    DealValue: "$325,000",
    Tags: "Pre-Approval",
    ExpectedCloseDate: "2026-05-30",
    Probability: "72%",
    Status: "Open",
    BorrowerName: "David Johnson",
    BorrowerPhone: "+1 (416) 555-0102",
    BorrowerEmail: "david.johnson@email.com",
    PropertyAddress: "456 Queen Street, Toronto, ON",
    PropertyType: "Condominium",
    LoanAmount: "$260,000",
    DownPayment: "$65,000",
    InterestRate: "5.34%",
    Lender: "TD Bank",
    LoanOfficer: "Mark Williams",
    Notes: "Looking to upgrade from rental",
  },
  {
    key: "3",
    DealName: "Williams LLC - Commercial",
    Stage: "Qualify To Buy",
    DealValue: "$1,200,000",
    Tags: "Commercial",
    ExpectedCloseDate: "2026-08-20",
    Probability: "68%",
    Status: "Open",
    BorrowerName: "Emma Williams",
    BorrowerPhone: "+1 (416) 555-0103",
    BorrowerEmail: "emma.williams@email.com",
    PropertyAddress: "789 King Street, Toronto, ON",
    PropertyType: "Commercial Building",
    LoanAmount: "$960,000",
    DownPayment: "$240,000",
    InterestRate: "6.15%",
    Lender: "Scotia Bank",
    LoanOfficer: "Jennifer Lee",
    Notes: "Commercial property for retail space",
  },
  {
    key: "4",
    DealName: "Brown Family - Townhouse",
    Stage: "Qualify To Buy",
    DealValue: "$275,000",
    Tags: "Renewal",
    ExpectedCloseDate: "2026-04-10",
    Probability: "90%",
    Status: "Open",
    BorrowerName: "Robert Brown",
    BorrowerPhone: "+1 (416) 555-0104",
    BorrowerEmail: "robert.brown@email.com",
    PropertyAddress: "321 Bloor Street, Toronto, ON",
    PropertyType: "Townhouse",
    LoanAmount: "$220,000",
    DownPayment: "$55,000",
    InterestRate: "5.19%",
    Lender: "CIBC",
    LoanOfficer: "David Park",
    Notes: "Mortgage renewal with rate improvement",
  },

  // ============================================================
  // CONTACT MADE - Documentation phase
  // ============================================================
  {
    key: "5",
    DealName: "Garcia Family - Semi-Detached",
    Stage: "Contact Made",
    DealValue: "$545,000",
    Tags: "Documentation",
    ExpectedCloseDate: "2026-05-15",
    Probability: "80%",
    Status: "Open",
    BorrowerName: "Carlos Garcia",
    BorrowerPhone: "+1 (416) 555-0105",
    BorrowerEmail: "carlos.garcia@email.com",
    PropertyAddress: "654 Dundas Street, Toronto, ON",
    PropertyType: "Semi-Detached",
    LoanAmount: "$436,000",
    DownPayment: "$109,000",
    InterestRate: "5.29%",
    Lender: "BMO",
    LoanOfficer: "Patricia Murphy",
    Notes: "Documents submitted, awaiting appraisal",
  },
  {
    key: "6",
    DealName: "Martinez Professional - Investment",
    Stage: "Contact Made",
    DealValue: "$650,000",
    Tags: "Investment",
    ExpectedCloseDate: "2026-07-01",
    Probability: "75%",
    Status: "Open",
    BorrowerName: "Luis Martinez",
    BorrowerPhone: "+1 (416) 555-0106",
    BorrowerEmail: "luis.martinez@email.com",
    PropertyAddress: "987 College Street, Toronto, ON",
    PropertyType: "Multi-Unit Investment",
    LoanAmount: "$520,000",
    DownPayment: "$130,000",
    InterestRate: "5.54%",
    Lender: "RBC",
    LoanOfficer: "Thomas Brady",
    Notes: "Investment property with rental income",
  },
  {
    key: "7",
    DealName: "Lee Family - House with Pool",
    Stage: "Contact Made",
    DealValue: "$725,000",
    Tags: "Premium",
    ExpectedCloseDate: "2026-06-30",
    Probability: "70%",
    Status: "Open",
    BorrowerName: "Susan Lee",
    BorrowerPhone: "+1 (416) 555-0107",
    BorrowerEmail: "susan.lee@email.com",
    PropertyAddress: "159 Avenue Road, Toronto, ON",
    PropertyType: "Luxury Home",
    LoanAmount: "$580,000",
    DownPayment: "$145,000",
    InterestRate: "5.44%",
    Lender: "TD Bank",
    LoanOfficer: "Michelle Zhang",
    Notes: "Premium property, high-value transaction",
  },

  // ============================================================
  // APPRAISAL - Property evaluation phase
  // ============================================================
  {
    key: "8",
    DealName: "Patel Family - Suburban Home",
    Stage: "Appraisal",
    DealValue: "$425,000",
    Tags: "Appraisal In Progress",
    ExpectedCloseDate: "2026-04-20",
    Probability: "88%",
    Status: "Open",
    BorrowerName: "Raj Patel",
    BorrowerPhone: "+1 (416) 555-0108",
    BorrowerEmail: "raj.patel@email.com",
    PropertyAddress: "456 Suburban Lane, Mississauga, ON",
    PropertyType: "Suburban Home",
    LoanAmount: "$340,000",
    DownPayment: "$85,000",
    InterestRate: "5.39%",
    Lender: "RBC",
    LoanOfficer: "James Wilson",
    Notes: "Appraisal scheduled for March 15",
  },
  {
    key: "9",
    DealName: "Anderson Couple - Estate",
    Stage: "Appraisal",
    DealValue: "$895,000",
    Tags: "Estate",
    ExpectedCloseDate: "2026-07-15",
    Probability: "82%",
    Status: "Open",
    BorrowerName: "John Anderson",
    BorrowerPhone: "+1 (416) 555-0109",
    BorrowerEmail: "john.anderson@email.com",
    PropertyAddress: "789 Forest Hill Road, Toronto, ON",
    PropertyType: "Estate Home",
    LoanAmount: "$716,000",
    DownPayment: "$179,000",
    InterestRate: "5.49%",
    Lender: "CIBC",
    LoanOfficer: "Elizabeth Brown",
    Notes: "Estate property with complex valuation",
  },

  // ============================================================
  // UNDERWRITING - Risk assessment phase
  // ============================================================
  {
    key: "10",
    DealName: "Thompson Family - Renovation",
    Stage: "Underwriting",
    DealValue: "$375,000",
    Tags: "Renovation",
    ExpectedCloseDate: "2026-03-25",
    Probability: "95%",
    Status: "Open",
    BorrowerName: "Elizabeth Thompson",
    BorrowerPhone: "+1 (416) 555-0110",
    BorrowerEmail: "elizabeth.thompson@email.com",
    PropertyAddress: "321 Renovation Drive, Toronto, ON",
    PropertyType: "Fixer-Upper",
    LoanAmount: "$300,000",
    DownPayment: "$75,000",
    InterestRate: "5.24%",
    Lender: "Scotiabank",
    LoanOfficer: "Robert Green",
    Notes: "Renovation mortgage, strong borrower profile",
  },
  {
    key: "11",
    DealName: "Kumar Professional - New Build",
    Stage: "Underwriting",
    DealValue: "$550,000",
    Tags: "New Build",
    ExpectedCloseDate: "2026-05-10",
    Probability: "92%",
    Status: "Open",
    BorrowerName: "Vikram Kumar",
    BorrowerPhone: "+1 (416) 555-0111",
    BorrowerEmail: "vikram.kumar@email.com",
    PropertyAddress: "111 New Development Ave, Brampton, ON",
    PropertyType: "New Build",
    LoanAmount: "$440,000",
    DownPayment: "$110,000",
    InterestRate: "5.34%",
    Lender: "BMO",
    LoanOfficer: "Jessica Kim",
    Notes: "New construction with builder incentives",
  },

  // ============================================================
  // FINAL APPROVAL - Closing preparation
  // ============================================================
  {
    key: "12",
    DealName: "Chen Family - Pre-Closing",
    Stage: "Final Approval",
    DealValue: "$625,000",
    Tags: "Pre-Closing",
    ExpectedCloseDate: "2026-03-20",
    Probability: "98%",
    Status: "Open",
    BorrowerName: "Wei Chen",
    BorrowerPhone: "+1 (416) 555-0112",
    BorrowerEmail: "wei.chen@email.com",
    PropertyAddress: "654 Final Street, Toronto, ON",
    PropertyType: "Single Family",
    LoanAmount: "$500,000",
    DownPayment: "$125,000",
    InterestRate: "5.19%",
    Lender: "TD Bank",
    LoanOfficer: "Susan Chen",
    Notes: "All documents reviewed, closing scheduled",
  },
  {
    key: "13",
    DealName: "Rodriguez Family - Bridge Loan",
    Stage: "Final Approval",
    DealValue: "$475,000",
    Tags: "Bridge",
    ExpectedCloseDate: "2026-03-18",
    Probability: "99%",
    Status: "Open",
    BorrowerName: "Miguel Rodriguez",
    BorrowerPhone: "+1 (416) 555-0113",
    BorrowerEmail: "miguel.rodriguez@email.com",
    PropertyAddress: "987 Final Avenue, Toronto, ON",
    PropertyType: "Townhouse",
    LoanAmount: "$380,000",
    DownPayment: "$95,000",
    InterestRate: "5.64%",
    Lender: "RBC",
    LoanOfficer: "Michael Torres",
    Notes: "Bridge financing approved",
  },

  // ============================================================
  // CLOSED/WON - Completed transactions
  // ============================================================
  {
    key: "14",
    DealName: "White Family - Closed Successfully",
    Stage: "Closed Won",
    DealValue: "$550,000",
    Tags: "Closed",
    ExpectedCloseDate: "2026-02-28",
    Probability: "100%",
    Status: "Won",
    BorrowerName: "James White",
    BorrowerPhone: "+1 (416) 555-0114",
    BorrowerEmail: "james.white@email.com",
    PropertyAddress: "123 Victory Lane, Toronto, ON",
    PropertyType: "Single Family",
    LoanAmount: "$440,000",
    DownPayment: "$110,000",
    InterestRate: "5.19%",
    Lender: "Scotiabank",
    LoanOfficer: "David Mitchell",
    Notes: "Successfully closed on February 28, 2026",
  },
  {
    key: "15",
    DealName: "Black Family - Closed Successfully",
    Stage: "Closed Won",
    DealValue: "$475,000",
    Tags: "Closed",
    ExpectedCloseDate: "2026-02-14",
    Probability: "100%",
    Status: "Won",
    BorrowerName: "Patricia Black",
    BorrowerPhone: "+1 (416) 555-0115",
    BorrowerEmail: "patricia.black@email.com",
    PropertyAddress: "456 Victory Road, Toronto, ON",
    PropertyType: "Semi-Detached",
    LoanAmount: "$380,000",
    DownPayment: "$95,000",
    InterestRate: "5.29%",
    Lender: "CIBC",
    LoanOfficer: "Laura Newman",
    Notes: "Successfully closed on February 14, 2026",
  },

  // ============================================================
  // LOST/CANCELLED - Deal lost transactions
  // ============================================================
  {
    key: "16",
    DealName: "Green Family - Cancelled",
    Stage: "Lost",
    DealValue: "$395,000",
    Tags: "Cancelled",
    ExpectedCloseDate: "2026-02-01",
    Probability: "0%",
    Status: "Lost",
    BorrowerName: "Thomas Green",
    BorrowerPhone: "+1 (416) 555-0116",
    BorrowerEmail: "thomas.green@email.com",
    PropertyAddress: "789 Lost Avenue, Toronto, ON",
    PropertyType: "Single Family",
    LoanAmount: "$316,000",
    DownPayment: "$79,000",
    InterestRate: "N/A",
    Lender: "None",
    LoanOfficer: "N/A",
    Notes: "Deal cancelled - borrower chose competitor",
  },
];

export const MortgageActivitiesData = [
  {
    key: "1",
    Title: "Pre-qualification meeting with Michael Smith",
    ActivityType: "Meeting",
    DueDate: "2026-03-10 10:00 AM",
    Owner: "Sarah Chen",
    CreatedAt: "2026-03-08 09:15 AM",
    Image: "avatar-01.jpg",
    DealId: "1",
  },
  {
    key: "2",
    Title: "Document package requested - Garcia family",
    ActivityType: "Email",
    DueDate: "2026-03-12 02:00 PM",
    Owner: "Patricia Murphy",
    CreatedAt: "2026-03-08 03:30 PM",
    Image: "avatar-02.jpg",
    DealId: "5",
  },
  {
    key: "3",
    Title: "Property appraisal scheduled",
    ActivityType: "Task",
    DueDate: "2026-03-15 08:00 AM",
    Owner: "James Wilson",
    CreatedAt: "2026-03-07 11:20 AM",
    Image: "avatar-03.jpg",
    DealId: "8",
  },
  {
    key: "4",
    Title: "Underwriting review - Thompson file",
    ActivityType: "Meeting",
    DueDate: "2026-03-11 03:00 PM",
    Owner: "Robert Green",
    CreatedAt: "2026-03-07 02:45 PM",
    Image: "avatar-04.jpg",
    DealId: "10",
  },
  {
    key: "5",
    Title: "Closing documents prepared and sent",
    ActivityType: "Email",
    DueDate: "2026-03-16 05:00 PM",
    Owner: "Susan Chen",
    CreatedAt: "2026-03-06 04:30 PM",
    Image: "avatar-05.jpg",
    DealId: "12",
  },
  {
    key: "6",
    Title: "Follow-up call with David Johnson",
    ActivityType: "Calls",
    DueDate: "2026-03-13 11:00 AM",
    Owner: "Mark Williams",
    CreatedAt: "2026-03-05 10:15 AM",
    Image: "avatar-06.jpg",
    DealId: "2",
  },
  {
    key: "7",
    Title: "Rate lock confirmation sent",
    ActivityType: "Email",
    DueDate: "2026-03-14 09:00 AM",
    Owner: "Jennifer Lee",
    CreatedAt: "2026-03-04 08:45 AM",
    Image: "avatar-07.jpg",
    DealId: "3",
  },
  {
    key: "8",
    Title: "Bridge loan approval notification",
    ActivityType: "Task",
    DueDate: "2026-03-17 10:00 AM",
    Owner: "Michael Torres",
    CreatedAt: "2026-03-03 09:30 AM",
    Image: "avatar-08.jpg",
    DealId: "13",
  },
];

export const MortgageApplicantsData = [
  {
    key: "1",
    Name: "Michael Smith",
    Role: "Primary Borrower",
    Phone: "+1 (416) 555-0101",
    Email: "michael.smith@email.com",
    Tags: "Pre-Qualified",
    Location: "Toronto, ON",
    Rating: "4.9",
    Image: "avatar-01.jpg",
    Status: "Active",
    Property: "123 Maple Street",
    LoanAmount: "$388,000",
    EmploymentStatus: "Employed",
  },
  {
    key: "2",
    Name: "David Johnson",
    Role: "Primary Borrower",
    Phone: "+1 (416) 555-0102",
    Email: "david.johnson@email.com",
    Tags: "Pre-Approved",
    Location: "Toronto, ON",
    Rating: "4.7",
    Image: "avatar-02.jpg",
    Status: "Active",
    Property: "456 Queen Street",
    LoanAmount: "$260,000",
    EmploymentStatus: "Employed",
  },
  {
    key: "3",
    Name: "Emma Williams",
    Role: "Primary Borrower",
    Phone: "+1 (416) 555-0103",
    Email: "emma.williams@email.com",
    Tags: "Commercial",
    Location: "Toronto, ON",
    Rating: "4.8",
    Image: "avatar-03.jpg",
    Status: "Active",
    Property: "789 King Street",
    LoanAmount: "$960,000",
    EmploymentStatus: "Self-Employed",
  },
  {
    key: "4",
    Name: "Robert Brown",
    Role: "Primary Borrower",
    Phone: "+1 (416) 555-0104",
    Email: "robert.brown@email.com",
    Tags: "Renewal",
    Location: "Toronto, ON",
    Rating: "4.9",
    Image: "avatar-04.jpg",
    Status: "Active",
    Property: "321 Bloor Street",
    LoanAmount: "$220,000",
    EmploymentStatus: "Employed",
  },
  {
    key: "5",
    Name: "Carlos Garcia",
    Role: "Primary Borrower",
    Phone: "+1 (416) 555-0105",
    Email: "carlos.garcia@email.com",
    Tags: "Documentation",
    Location: "Toronto, ON",
    Rating: "4.6",
    Image: "avatar-05.jpg",
    Status: "Active",
    Property: "654 Dundas Street",
    LoanAmount: "$436,000",
    EmploymentStatus: "Employed",
  },
  {
    key: "6",
    Name: "Raj Patel",
    Role: "Primary Borrower",
    Phone: "+1 (416) 555-0108",
    Email: "raj.patel@email.com",
    Tags: "Appraisal",
    Location: "Mississauga, ON",
    Rating: "4.8",
    Image: "avatar-06.jpg",
    Status: "Active",
    Property: "456 Suburban Lane",
    LoanAmount: "$340,000",
    EmploymentStatus: "Employed",
  },
  {
    key: "7",
    Name: "Wei Chen",
    Role: "Primary Borrower",
    Phone: "+1 (416) 555-0112",
    Email: "wei.chen@email.com",
    Tags: "Pre-Closing",
    Location: "Toronto, ON",
    Rating: "4.9",
    Image: "avatar-07.jpg",
    Status: "Active",
    Property: "654 Final Street",
    LoanAmount: "$500,000",
    EmploymentStatus: "Employed",
  },
  {
    key: "8",
    Name: "James White",
    Role: "Primary Borrower",
    Phone: "+1 (416) 555-0114",
    Email: "james.white@email.com",
    Tags: "Closed",
    Location: "Toronto, ON",
    Rating: "5.0",
    Image: "avatar-08.jpg",
    Status: "Inactive",
    Property: "123 Victory Lane",
    LoanAmount: "$440,000",
    EmploymentStatus: "Employed",
  },
];

export const MortgageLeadsData = [
  {
    key: "1",
    LeadImage: "avatar-01.jpg",
    LeadName: "John Anderson",
    CompanyName: "Anderson & Associates",
    Location: "Toronto, ON",
    CompanyImage: "company-icon-01.svg",
    Phone: "+1 (416) 555-0120",
    LeadStatus: "Contacted",
    LeadOwner: "Sarah Chen",
    OwnerImage: "avatar-01.jpg",
    CreatedDate: "2026-03-05 10:30 AM",
    PropertyInterest: "Single Family Home",
    BudgetRange: "$400K - $600K",
  },
  {
    key: "2",
    LeadImage: "avatar-02.jpg",
    LeadName: "Maria Rodriguez",
    CompanyName: "Rodriguez Enterprises",
    Location: "Mississauga, ON",
    CompanyImage: "company-icon-02.svg",
    Phone: "+1 (416) 555-0121",
    LeadStatus: "Qualified",
    LeadOwner: "Mark Williams",
    OwnerImage: "avatar-02.jpg",
    CreatedDate: "2026-03-04 02:15 PM",
    PropertyInterest: "Investment Property",
    BudgetRange: "$700K - $1M",
  },
  {
    key: "3",
    LeadImage: "avatar-03.jpg",
    LeadName: "Kevin Park",
    CompanyName: "Park Financial Group",
    Location: "Toronto, ON",
    CompanyImage: "company-icon-03.svg",
    Phone: "+1 (416) 555-0122",
    LeadStatus: "Not Contacted",
    LeadOwner: "Jennifer Lee",
    OwnerImage: "avatar-03.jpg",
    CreatedDate: "2026-03-03 11:45 AM",
    PropertyInterest: "Commercial Building",
    BudgetRange: "$1M+",
  },
  {
    key: "4",
    LeadImage: "avatar-04.jpg",
    LeadName: "Lisa Thompson",
    CompanyName: "Thompson Development",
    Location: "Brampton, ON",
    CompanyImage: "company-icon-04.svg",
    Phone: "+1 (416) 555-0123",
    LeadStatus: "Contacted",
    LeadOwner: "Robert Green",
    OwnerImage: "avatar-04.jpg",
    CreatedDate: "2026-03-02 03:20 PM",
    PropertyInterest: "New Build",
    BudgetRange: "$450K - $650K",
  },
  {
    key: "5",
    LeadImage: "avatar-05.jpg",
    LeadName: "Marcus Johnson",
    CompanyName: "Johnson Holdings",
    Location: "Toronto, ON",
    CompanyImage: "company-icon-05.svg",
    Phone: "+1 (416) 555-0124",
    LeadStatus: "Qualified",
    LeadOwner: "Patricia Murphy",
    OwnerImage: "avatar-05.jpg",
    CreatedDate: "2026-03-01 09:00 AM",
    PropertyInterest: "Multi-Unit Residential",
    BudgetRange: "$800K - $1.2M",
  },
];
